version: '3'

volumes:
  redis_data:
  media_file:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - media_file:/app/media

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/

  celery:
    build: .
    command: celery -A khalifa worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
