version: '3'

services:
  web:
    build: .
    command: gunicorn khalifa.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file:/media
      - static_file:/khalifa/static

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/media
      - static_file:/khalifa/static
    depends_on:
      - web

volumes:
  media_file:
  static_file: